/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/home/index" |
       "/pages/demo/index" |
       "/pages/create_profile/index" |
       "/pages/create_sound/index" |
       "/pages/digital_people/index" |
       "/pages/login/bind" |
       "/pages/login/index" |
       "/pages/product/index" |
       "/pages/user/index" |
       "/pages/create_sound/components/SoundPop" |
       "/pages/digital_people/components/SelectProfilePop" |
       "/pages/digital_people/components/SelectTonePop" |
       "/pages/product/components/ProductList" |
       "/pages/user/components/KefuPop" |
       "/pages/user/components/UserService" |
       "/bundle/pages/agreement/index" |
       "/bundle/pages/article/index" |
       "/bundle/pages/article_detail/index" |
       "/bundle/pages/hashrate/index" |
       "/bundle/pages/hashrate_log/index" |
       "/bundle/pages/user_set/index" |
       "/bundle/pages/profile/index" |
       "/bundle/pages/change_nickname/index" |
       "/bundle/pages/change_mobile/index" |
       "/bundle/pages/change_password/index" |
       "/bundle/pages/play_video/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/home/index" | "/pages/product/index" | "/pages/user/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
